// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manufacturermodeldata.proto

package com.stupidbeauty.comgooglewidevinesoftwaredrmremover;

public final class ManufacturerModelMessageProtos {
  private ManufacturerModelMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ManufacturerModelDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    java.util.List<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer> 
        getManufacturersList();
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer getManufacturers(int index);
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    int getManufacturersCount();
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    java.util.List<? extends com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder> 
        getManufacturersOrBuilderList();
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder getManufacturersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelData}
   */
  public  static final class ManufacturerModelData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelData)
      ManufacturerModelDataOrBuilder {
    // Use ManufacturerModelData.newBuilder() to construct.
    private ManufacturerModelData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ManufacturerModelData() {
      manufacturers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ManufacturerModelData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                manufacturers_ = new java.util.ArrayList<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer>();
                mutable_bitField0_ |= 0x00000001;
              }
              manufacturers_.add(
                  input.readMessage(com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          manufacturers_ = java.util.Collections.unmodifiableList(manufacturers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData.class, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData.Builder.class);
    }

    public static final int MANUFACTURERS_FIELD_NUMBER = 1;
    private java.util.List<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer> manufacturers_;
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    public java.util.List<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer> getManufacturersList() {
      return manufacturers_;
    }
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    public java.util.List<? extends com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder> 
        getManufacturersOrBuilderList() {
      return manufacturers_;
    }
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    public int getManufacturersCount() {
      return manufacturers_.size();
    }
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer getManufacturers(int index) {
      return manufacturers_.get(index);
    }
    /**
     * <pre>
     *厂商列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
     */
    public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder getManufacturersOrBuilder(
        int index) {
      return manufacturers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < manufacturers_.size(); i++) {
        output.writeMessage(1, manufacturers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < manufacturers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, manufacturers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData)) {
        return super.equals(obj);
      }
      com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData other = (com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData) obj;

      boolean result = true;
      result = result && getManufacturersList()
          .equals(other.getManufacturersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getManufacturersCount() > 0) {
        hash = (37 * hash) + MANUFACTURERS_FIELD_NUMBER;
        hash = (53 * hash) + getManufacturersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelData)
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData.class, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData.Builder.class);
      }

      // Construct using com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getManufacturersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (manufacturersBuilder_ == null) {
          manufacturers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          manufacturersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_descriptor;
      }

      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData getDefaultInstanceForType() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData.getDefaultInstance();
      }

      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData build() {
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData buildPartial() {
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData result = new com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData(this);
        int from_bitField0_ = bitField0_;
        if (manufacturersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            manufacturers_ = java.util.Collections.unmodifiableList(manufacturers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.manufacturers_ = manufacturers_;
        } else {
          result.manufacturers_ = manufacturersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData) {
          return mergeFrom((com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData other) {
        if (other == com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData.getDefaultInstance()) return this;
        if (manufacturersBuilder_ == null) {
          if (!other.manufacturers_.isEmpty()) {
            if (manufacturers_.isEmpty()) {
              manufacturers_ = other.manufacturers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureManufacturersIsMutable();
              manufacturers_.addAll(other.manufacturers_);
            }
            onChanged();
          }
        } else {
          if (!other.manufacturers_.isEmpty()) {
            if (manufacturersBuilder_.isEmpty()) {
              manufacturersBuilder_.dispose();
              manufacturersBuilder_ = null;
              manufacturers_ = other.manufacturers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              manufacturersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getManufacturersFieldBuilder() : null;
            } else {
              manufacturersBuilder_.addAllMessages(other.manufacturers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer> manufacturers_ =
        java.util.Collections.emptyList();
      private void ensureManufacturersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          manufacturers_ = new java.util.ArrayList<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer>(manufacturers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder> manufacturersBuilder_;

      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public java.util.List<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer> getManufacturersList() {
        if (manufacturersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(manufacturers_);
        } else {
          return manufacturersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public int getManufacturersCount() {
        if (manufacturersBuilder_ == null) {
          return manufacturers_.size();
        } else {
          return manufacturersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer getManufacturers(int index) {
        if (manufacturersBuilder_ == null) {
          return manufacturers_.get(index);
        } else {
          return manufacturersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder setManufacturers(
          int index, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer value) {
        if (manufacturersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureManufacturersIsMutable();
          manufacturers_.set(index, value);
          onChanged();
        } else {
          manufacturersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder setManufacturers(
          int index, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder builderForValue) {
        if (manufacturersBuilder_ == null) {
          ensureManufacturersIsMutable();
          manufacturers_.set(index, builderForValue.build());
          onChanged();
        } else {
          manufacturersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder addManufacturers(com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer value) {
        if (manufacturersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureManufacturersIsMutable();
          manufacturers_.add(value);
          onChanged();
        } else {
          manufacturersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder addManufacturers(
          int index, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer value) {
        if (manufacturersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureManufacturersIsMutable();
          manufacturers_.add(index, value);
          onChanged();
        } else {
          manufacturersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder addManufacturers(
          com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder builderForValue) {
        if (manufacturersBuilder_ == null) {
          ensureManufacturersIsMutable();
          manufacturers_.add(builderForValue.build());
          onChanged();
        } else {
          manufacturersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder addManufacturers(
          int index, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder builderForValue) {
        if (manufacturersBuilder_ == null) {
          ensureManufacturersIsMutable();
          manufacturers_.add(index, builderForValue.build());
          onChanged();
        } else {
          manufacturersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder addAllManufacturers(
          java.lang.Iterable<? extends com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer> values) {
        if (manufacturersBuilder_ == null) {
          ensureManufacturersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, manufacturers_);
          onChanged();
        } else {
          manufacturersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder clearManufacturers() {
        if (manufacturersBuilder_ == null) {
          manufacturers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          manufacturersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public Builder removeManufacturers(int index) {
        if (manufacturersBuilder_ == null) {
          ensureManufacturersIsMutable();
          manufacturers_.remove(index);
          onChanged();
        } else {
          manufacturersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder getManufacturersBuilder(
          int index) {
        return getManufacturersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder getManufacturersOrBuilder(
          int index) {
        if (manufacturersBuilder_ == null) {
          return manufacturers_.get(index);  } else {
          return manufacturersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public java.util.List<? extends com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder> 
           getManufacturersOrBuilderList() {
        if (manufacturersBuilder_ != null) {
          return manufacturersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(manufacturers_);
        }
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder addManufacturersBuilder() {
        return getManufacturersFieldBuilder().addBuilder(
            com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.getDefaultInstance());
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder addManufacturersBuilder(
          int index) {
        return getManufacturersFieldBuilder().addBuilder(
            index, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.getDefaultInstance());
      }
      /**
       * <pre>
       *厂商列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer manufacturers = 1;</code>
       */
      public java.util.List<com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder> 
           getManufacturersBuilderList() {
        return getManufacturersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder> 
          getManufacturersFieldBuilder() {
        if (manufacturersBuilder_ == null) {
          manufacturersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder>(
                  manufacturers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          manufacturers_ = null;
        }
        return manufacturersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelData)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelData)
    private static final com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData();
    }

    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ManufacturerModelData>
        PARSER = new com.google.protobuf.AbstractParser<ManufacturerModelData>() {
      public ManufacturerModelData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ManufacturerModelData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ManufacturerModelData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ManufacturerModelData> getParserForType() {
      return PARSER;
    }

    public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerModelData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ManufacturerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    java.util.List<java.lang.String>
        getModelsList();
    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    int getModelsCount();
    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    java.lang.String getModels(int index);
    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    com.google.protobuf.ByteString
        getModelsBytes(int index);

    /**
     * <pre>
     *厂商名字。
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     *厂商名字。
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *厂商名字。
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer}
   */
  public  static final class Manufacturer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer)
      ManufacturerOrBuilder {
    // Use Manufacturer.newBuilder() to construct.
    private Manufacturer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Manufacturer() {
      models_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Manufacturer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                models_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              models_.add(bs);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          models_ = models_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.class, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder.class);
    }

    private int bitField0_;
    public static final int MODELS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList models_;
    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getModelsList() {
      return models_;
    }
    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    public int getModelsCount() {
      return models_.size();
    }
    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    public java.lang.String getModels(int index) {
      return models_.get(index);
    }
    /**
     * <pre>
     *型号列表。
     * </pre>
     *
     * <code>repeated string models = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelsBytes(int index) {
      return models_.getByteString(index);
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *厂商名字。
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *厂商名字。
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *厂商名字。
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < models_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, models_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < models_.size(); i++) {
          dataSize += computeStringSizeNoTag(models_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getModelsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer)) {
        return super.equals(obj);
      }
      com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer other = (com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer) obj;

      boolean result = true;
      result = result && getModelsList()
          .equals(other.getModelsList());
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getModelsCount() > 0) {
        hash = (37 * hash) + MODELS_FIELD_NUMBER;
        hash = (53 * hash) + getModelsList().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer)
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.ManufacturerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.class, com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.Builder.class);
      }

      // Construct using com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        models_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_descriptor;
      }

      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer getDefaultInstanceForType() {
        return com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.getDefaultInstance();
      }

      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer build() {
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer buildPartial() {
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer result = new com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          models_ = models_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.models_ = models_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer) {
          return mergeFrom((com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer other) {
        if (other == com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer.getDefaultInstance()) return this;
        if (!other.models_.isEmpty()) {
          if (models_.isEmpty()) {
            models_ = other.models_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureModelsIsMutable();
            models_.addAll(other.models_);
          }
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList models_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureModelsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          models_ = new com.google.protobuf.LazyStringArrayList(models_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getModelsList() {
        return models_.getUnmodifiableView();
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public int getModelsCount() {
        return models_.size();
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public java.lang.String getModels(int index) {
        return models_.get(index);
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public com.google.protobuf.ByteString
          getModelsBytes(int index) {
        return models_.getByteString(index);
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public Builder setModels(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModelsIsMutable();
        models_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public Builder addModels(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModelsIsMutable();
        models_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public Builder addAllModels(
          java.lang.Iterable<java.lang.String> values) {
        ensureModelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, models_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public Builder clearModels() {
        models_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *型号列表。
       * </pre>
       *
       * <code>repeated string models = 1;</code>
       */
      public Builder addModelsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModelsIsMutable();
        models_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *厂商名字。
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *厂商名字。
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *厂商名字。
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *厂商名字。
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *厂商名字。
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *厂商名字。
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.comgooglewidevinesoftwaredrmremover.Manufacturer)
    private static final com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer();
    }

    public static com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Manufacturer>
        PARSER = new com.google.protobuf.AbstractParser<Manufacturer>() {
      public Manufacturer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Manufacturer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Manufacturer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Manufacturer> getParserForType() {
      return PARSER;
    }

    public com.stupidbeauty.comgooglewidevinesoftwaredrmremover.ManufacturerModelMessageProtos.Manufacturer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033manufacturermodeldata.proto\0224com.stupi" +
      "dbeauty.comgooglewidevinesoftwaredrmremo" +
      "ver\"r\n\025ManufacturerModelData\022Y\n\rmanufact" +
      "urers\030\001 \003(\0132B.com.stupidbeauty.comgoogle" +
      "widevinesoftwaredrmremover.Manufacturer\"" +
      ",\n\014Manufacturer\022\016\n\006models\030\001 \003(\t\022\014\n\004name\030" +
      "\002 \001(\tBV\n4com.stupidbeauty.comgooglewidev" +
      "inesoftwaredrmremoverB\036ManufacturerModel" +
      "MessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_ManufacturerModelData_descriptor,
        new java.lang.String[] { "Manufacturers", });
    internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_comgooglewidevinesoftwaredrmremover_Manufacturer_descriptor,
        new java.lang.String[] { "Models", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
